// src/routes/about/+page.svelte
<main class="about">
  <div class="languages">
    <h1>Languages</h1>
    <ul class="languages_items">
      <li>
        <a href="https://www.typescriptlang.org/">
          <img
            src="https://img.shields.io/badge/-TypeScript-%233178C6?style=for-the-badge&logo=typescript&logoColor=white"
            alt="TypeScript"
            width="126.5"
            height="28"
          />
        </a>
      </li>
      <li>
        <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript">
          <img
            src="https://img.shields.io/badge/-Javascript-%23F7DF1E?style=for-the-badge&logo=javascript&logoColor=black"
            alt="JavaScript"
            width="126.5"
            height="28"
          />
        </a>
      </li>
    </ul>
  </div>
  <div class="devOps">
    <h1>DevOps</h1>
    <ul class="devOps_items">
      <li>
        <a href="https://code.visualstudio.com/">
          <img
            src="https://img.shields.io/badge/-Visual_Studio_Code-%23007ACC?style=for-the-badge&logo=visualstudiocode&logoColor=white"
            alt="Visual Studio Code"
            width="190.5"
            height="28"
          />
        </a>
      </li>
      <li>
        <a href="https://archlinux.org">
          <img
            src="https://img.shields.io/badge/-ArchLinux-%231793D1?style=for-the-badge&logo=archlinux&logoColor=white"
            alt="ArchLinux"
            width="122.5"
            height="28"
          />
        </a>
      </li>
      <li>
        <a href="https://git-scm.com/">
          <img
            src="https://img.shields.io/badge/-Git-%23F05032?style=for-the-badge&logo=git&logoColor=white"
            alt="Git"
            width="67.5"
            height="28"
          />
        </a>
      </li>
      <li>
        <a href="https://docker.com">
          <img
            src="https://img.shields.io/badge/-Docker-%232496ED?style=for-the-badge&logo=docker&logoColor=white"
            alt="Docker"
            width="97.5"
            height="28"
          />
        </a>
      </li>
      <li>
        <a href="https://mariadb.org/">
          <img
            src="https://img.shields.io/badge/-MariaDB-%23003545?style=for-the-badge&logo=mariadb&logoColor=white"
            alt="MariaDB"
            width="106.5"
            height="28"
          />
        </a>
      </li>
    </ul>
  </div>
</main>

<style>
  .languages {
    margin-left: 25%;
  }

  .languages h1 {
    font-size: 50px;
  }

  .languages_items {
    list-style: none;
    padding-inline-start: 25%;
  }

  .about {
    display: flex;
  }

  .devOps {
    margin-left: 25%;
    text-align: center;
  }

  .devOps h1 {
    font-size: 50px;
  }

  .devOps_items {
    list-style: none;
    padding-inline-start: 0;
  }
</style>

// src/pages/about/index.tsx
import styles from '@/styles/About.module.css'
import Image from 'next/image'
import Link from 'next/link'

export default function About() {
  return (
    <main className={styles.about}>
      <div className={styles.languages}>
        <h1>Languages</h1>
        <ul className={styles.languages_items}>
          <li>
            <Link href={'https://www.typescriptlang.org/'}>
              <Image
                src={
                  'https://img.shields.io/badge/-TypeScript-%233178C6?style=for-the-badge&logo=typescript&logoColor=white'
                }
                alt={'TypeScript'}
                width={126.5}
                height={28}
              />
            </Link>
          </li>
          <li>
            <Link
              href={'https://developer.mozilla.org/en-US/docs/Web/JavaScript'}
            >
              <Image
                src={
                  'https://img.shields.io/badge/-Javascript-%23F7DF1E?style=for-the-badge&logo=javascript&logoColor=black'
                }
                alt={'JavaScript'}
                width={126.5}
                height={28}
              />
            </Link>
          </li>
        </ul>
      </div>
      <div className={styles.devOps}>
        <h1>DevOps</h1>
        <ul className={styles.devOps_items}>
          <li>
            <Link href={'https://code.visualstudio.com/'}>
              <Image
                src={
                  'https://img.shields.io/badge/-Visual_Studio_Code-%23007ACC?style=for-the-badge&logo=visualstudiocode&logoColor=white'
                }
                alt={'Visual Studio Code'}
                width={190.5}
                height={28}
              />
            </Link>
          </li>
          <li>
            <Link href={'https://archlinux.org'}>
              <Image
                src={
                  'https://img.shields.io/badge/-ArchLinux-%231793D1?style=for-the-badge&logo=archlinux&logoColor=white'
                }
                alt={'ArchLinux'}
                width={122.5}
                height={28}
              />
            </Link>
          </li>
          <li>
            <Link href={'https://git-scm.com/'}>
              <Image
                src={
                  'https://img.shields.io/badge/-Git-%23F05032?style=for-the-badge&logo=git&logoColor=white'
                }
                alt={'Git'}
                width={67.5}
                height={28}
              />
            </Link>
          </li>
          <li>
            <Link href={'https://docker.com'}>
              <Image
                src={
                  'https://img.shields.io/badge/-Docker-%232496ED?style=for-the-badge&logo=docker&logoColor=white'
                }
                alt={'Docker'}
                width={97.5}
                height={28}
              />
            </Link>
          </li>
          <li>
            <Link href={'https://mariadb.org/'}>
              <Image
                src={
                  'https://img.shields.io/badge/-MariaDB-%23003545?style=for-the-badge&logo=mariadb&logoColor=white'
                }
                alt={'MariaDB'}
                width={106.5}
                height={28}
              />
            </Link>
          </li>
        </ul>
      </div>
    </main>
  )
}
